version: '3'

services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:10.4
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
